:markup-in-source: verbatim,attributes,quotes

== Create an admin user for quick access

If you want to be able to access your cluster immediately through a cluster-admin user, you can follow these steps.

This is good if you need quick access to the cluster, which is great for this workshop.

Though the recommended approach is to use a formal identity provider to access the cluster (and then grant that user admin privileges, if desired).

. Run this command to create the admin user
+
[source,sh,role=execute]
----
rosa create admin --cluster ${CLUSTER_NAME} | tee $HOME/${CLUSTER_NAME}.cmd
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Admin account has been added to cluster 'rosa-4fgbq'.
I: Please securely store this generated password. If you lose this password you can delete and recreate the cluster admin user.
I: To login, run the following command:

   oc login https://api.rosa-4fgbq.qrdf.p1.openshiftapps.com:6443 --username cluster-admin --password cD4xo-AnanH-DvB6L-6yndM

I: It may take several minutes for this access to become active.
----
+
[TIP]
====
The command above also saves the login command to the `$HOME/${CLUSTER_NAME}.cmd` file for future reference.

*Make sure to use the entire password when copying and pasting the command!*
====

. Save an environment variable for your admin password (copy the password from above making sure to copy the *entire* password):
+
.Note this box will not automatically copy the command for you. You need to write the command yourself.
[source,sh]
----
export ADMIN_PASSWORD=cD4xo-AnanH-DvB6L-6yndM
----
+
Save the admin password in your `.bashrc`
+
[source,sh,role=execute]
----
echo "export ADMIN_PASSWORD=${ADMIN_PASSWORD}" >>$HOME/.bashrc
----

. Copy the login command returned to you in the previous step and paste that into your terminal. This should log you into the cluster via the CLI so you can start using the cluster (answer `y` when promted if you want to accept the certificate).
+
[source,sh]
----
oc login ${API_URL} --username cluster-admin --password ${ADMIN_PASSWORD}
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
The server uses a certificate signed by an unknown authority.
You can bypass the certificate check, but any data you send to the server could be intercepted by others.
Use insecure connections? (y/n): y

WARNING: Using insecure TLS client config. Setting this option is not supported!

Login successful.

You have access to 101 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
----
+
[TIP]
====
If you get an error that the *Login failed (401 Unauthorized)* wait a few seconds and then try again. It takes a few minutes for the cluster authentication operator to update itself after creating the cluster admin user.
====

. To check that you are logged in as the admin user you can run `oc whoami`:
+
[source,sh,role=execute]
----
oc whoami
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
cluster-admin
----

. You can also confirm by running the following command. Only a cluster-admin user can run this without errors.
// +
// Also these pods may not yet exist or be in `Pending` status depending on how long it's been since your control plane finished installing.
+
[source,sh,role=execute]
----
oc get pod -n openshift-ingress
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
NAME                              READY   STATUS    RESTARTS   AGE
router-default-7994f6fd58-8cl45   1/1     Running   0          102s
router-default-7994f6fd58-z6gpm   1/1     Running   0          102s
----

. You can now use the cluster as an admin user, which will suffice for this workshop. Though, for any other use, it is highly recommended to set up an IdP.

=== Login to the OpenShift Web Console

Next, let's log in to the OpenShift Web Console. To do so, follow the below steps:

. First, we'll need to grab your cluster's web console URL. To do so, run the following command:
+
[source,sh,role=execute]
----
oc whoami --show-console
----
+
.Sample Output
[source,text,options=nowrap]
----
https://console-openshift-console.%rosa_subdomain_base%
----

. Next, open the printed URL in a web browser.
. Enter the username (`cluster-admin`) and password from the previous section (use `echo ${ADMIN_PASSWORD}` to remind yourself what the password is in case you forgot).
+
If you don't see an error, congratulations! You're now logged into the cluster and ready to move on to the workshop content.
