== The Workshop Environment You Are Using

Your environment has already been set up and you are ready to deploy your first ROSA cluster.

Your workshop environment consists of several components which have been pre-configured and are ready to use.
This includes a %aws_web_console_url%[Amazon Web Services (AWS)] account, and many other supporting resources.

ROSA is enabled on the AWS account used for this lab - and the ROSA CLI as well as AWS CLI tools are installed and configured on your bastion VM.

== Connect to your bastion VM

. In the terminal window to the right connect to the bastion VM (you can also just click the command below to have it copied and executed automatically):
+
[TIP]
====
Answer `yes` when asked if to accept the host key.

The password for the user %rosa_bastion_user_name% is `%rosa_user_password%`
====
+
[source,sh,role=copy]
----
ssh %rosa_bastion_user_name%@bastion.%rosa_subdomain_base%
----
+
.Click in the box below to copy and paste the string `yes` to your terminal:
+
[source,sh,role=copy]
----
yes
----
+
.Click in the box below to copy and paste the password to your terminal:
+
[source,sh,role=copy]
----
%rosa_user_password%
----

=== Validate installed tools

You will be using the `rosa`, `aws` and `oc` command line tools throughout this lab.

. Verify that the `rosa` command line tool is installed (note that your version may be a more recent version than the output shown below):
+
[source,sh,role=copy]
----
rosa version
----
+
.Sample Output
[source,texinfo]
----
1.2.24
I: Your ROSA CLI is up to date.
----

. Verify that the `aws` command line tool is installed:
+
[source,sh,role=copy]
----
aws --version
----
+
.Sample Output
[source,text,options=nowrap]
----
aws-cli/2.13.6 Python/3.11.4 Linux/5.14.0-284.25.1.el9_2.x86_64 exe/x86_64.rhel.9 prompt/off
----

. Verify that the `aws` command line tool is configured correctly:
+
[source,sh,role=copy]
----
aws sts get-caller-identity
----
+
.Sample Output
[source,texinfo]
----
{
    "UserId": "AIDA52VPS74UJLY4GUW7L",
    "Account": "950629760808",
    "Arn": "arn:aws:iam::950629760808:user/wkulhane@redhat.com-nhnv4"
}
----

. Verify that the `oc` CLI is installed correctly
+
[source,sh,role=copy]
----
rosa verify openshift-client
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Verifying whether OpenShift command-line tool is available...
I: Current OpenShift Client Version: 4.13.6
----

. Rosa login
+
[source,sh,role=copy]
----
rosa login
----
+
.Sample Output
[source,texinfo]
----
I: Logged in as 'rhpds-cloud' on 'https://api.openshift.com'
----
+
[NOTE]
====
Normally you would need to get a *token* from the https://console.redhat.com/openshift/token/rosa)[Red Hat Console] and log into ROSA using that token.

In this environment your token has been preconfigured for you.
====

. Run rosa whoami to verify your credentials:
+
[source,sh,role=copy]
----
rosa whoami
----
+
.Sample Output
[source,texinfo]
----
AWS ARN:                      arn:aws:iam::<redacted>:user/wkulhane@redhat.com-nhnv4
AWS Account ID:               <redacted>
AWS Default Region:           us-east-2
OCM API:                      https://api.openshift.com
OCM Account Email:            rhpds-admins+cloud@redhat.com
OCM Account ID:               <redacted>
OCM Account Name:             RHPDS Cloud
OCM Account Username:         rhpds-cloud
OCM Organization External ID: <redacted>
OCM Organization ID:          <redacted>
OCM Organization Name:        Red Hat, Inc.
----

// === Install OCM

// You will need to use the OpenShift Cluster Manager (ocm) to do some tasks in these labs.

// . Set the OCM Release to download (at time of writing this was `0.1.67` - you can check at https://github.com/openshift-online/ocm-cli/releases if there is anything newer available):
// +
// [source,sh]
// ----
// export OCM_RELEASE=v0.1.67
// ----

// . Download the latest OCM release
// +
// [source,sh]
// ----
// # Check that ${HOME}/bin exists
// if [ ! -d "${HOME}/bin" ]; then
//   mkdir ${HOME}/bin
// fi

// wget -O ${HOME}/bin/ocm https://github.com/openshift-online/ocm-cli/releases/download/${OCM_RELEASE}/ocm-linux-amd64

// chmod +x ${HOME}/bin/ocm

// ocm version
// ----
// +
// .Sample Output
// [source,texinfo]
// ----
// 0.1.67
// ----

=== Verify quota

. Verify that your AWS account has enough quota in the region you will be deploying your cluster to.
+
[source,sh,role=copy]
----
rosa verify quota
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
I: Validating AWS quota...
I: AWS quota ok. If cluster installation fails, validate actual AWS resource usage against https://docs.openshift.com/
rosa/rosa_getting_started/rosa-required-aws-service-quotas.html
----
+
See https://docs.openshift.com/rosa/rosa_planning/rosa-sts-required-aws-service-quotas.html[the documentation] for more details regarding quotas.

We have now successfully set up our account and environment and are ready to deploy our cluster.
