= Using AWS Secrets Manager CSI

The AWS Secrets and Configuration Provider (ASCP) provides a way to expose AWS Secrets as Kubernetes storage volumes. With the ASCP, you can store and manage your secrets in Secrets Manager and then retrieve them through your workloads running on ROSA or OSD.

This is made even easier and more secure through the use of AWS STS and Kubernetes PodIdentity.

== Preparing Environment

. Validate that your cluster has been deployed using STS:
+
[source,sh,role=copy]
----
oc get authentication.config.openshift.io cluster -o json | jq .spec.serviceAccountIssuer
----
+
.Sample Output
[source,texinfo]
----
"https://rh-oidc.s3.us-east-1.amazonaws.com/256i475s1nnuaobmhd8hobotj7c6ufpb"
----
+
You should see something like the line in the sample output, if not you should not proceed.

. Set SecurityContextConstraints to allow the CSI driver to run
+
[source,sh,role=copy]
----
oc new-project csi-secrets-store

oc adm policy add-scc-to-user privileged \
  system:serviceaccount:csi-secrets-store:secrets-store-csi-driver

oc adm policy add-scc-to-user privileged \
  system:serviceaccount:csi-secrets-store:csi-secrets-store-provider-aws
----

. Create some environment variables to refer to later
+
[source,sh,role=copy]
----
export OIDC_ENDPOINT=$(oc get authentication.config.openshift.io cluster \
  -o jsonpath='{.spec.serviceAccountIssuer}' | sed  's|^https://||')

export AWS_ACCOUNT_ID=`aws sts get-caller-identity --query Account --output text`

export AWS_PAGER=""

export SECRETS_DIR=${HOME}/secrets
mkdir -p ${SECRETS_DIR}
----

. Deploy the AWS Secrets and Configuration Provider. Use Helm to register the secrets store csi driver:
+
[source,sh,role=copy]
----
helm repo add secrets-store-csi-driver \
  https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts

helm repo update
----

. Install the secrets store csi driver:
+
[source,sh,role=copy]
----
helm install -n csi-secrets-store \
  csi-secrets-store-driver \
  secrets-store-csi-driver/secrets-store-csi-driver \
  --set-json commonLabels='{"security.openshift.io/csi-ephemeral-volume-profile":"restricted"}'
----

. Download the AWS provider definition:
+
[source,sh,role=copy]
----
wget -O ${SECRETS_DIR}/aws-provider-installer.yaml https://raw.githubusercontent.com/aws/secrets-store-csi-driver-provider-aws/main/deployment/aws-provider-installer.yaml
----

. Change it to run on our cluster:
+
[source,sh,role=copy]
----
sed -i 's/  namespace\: kube-system/  namespace\: csi-secrets-store/g' ${SECRETS_DIR}/aws-provider-installer.yaml

sed -i 's/      hostNetwork\: false/      hostNetwork\: true/g' ${SECRETS_DIR}/aws-provider-installer.yaml
----

// Remove the 3 lines starting with `securityContext:` ... does not seem to be necessary anymore
. Create the daemon set:
+
[source,sh,role=copy]
----
oc apply -f ${SECRETS_DIR}/aws-provider-installer.yaml
----
+
.Sample Output
[source,texinfo]
----
serviceaccount/csi-secrets-store-provider-aws unchanged
clusterrole.rbac.authorization.k8s.io/csi-secrets-store-provider-aws-cluster-role created
clusterrolebinding.rbac.authorization.k8s.io/csi-secrets-store-provider-aws-cluster-rolebinding configured
daemonset.apps/csi-secrets-store-provider-aws created
----

. Check that both Daemonsets are running
+
[source,sh,role=copy]
----
oc -n csi-secrets-store get ds \
  csi-secrets-store-provider-aws \
  csi-secrets-store-driver-secrets-store-csi-driver
----
+
.Sample Output
[source,texinfo,options=nowrap]
----
NAME                                                DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
csi-secrets-store-provider-aws                      2         2         2       2            2           kubernetes.io/os=linux   113s
csi-secrets-store-driver-secrets-store-csi-driver   7         7         7       7            7           kubernetes.io/os=linux   50m
----

== Creating a Secret and IAM Access Policies

. Create a secret in AWS Secrets Manager:
+
[source,sh,role=copy]
----
SECRET_ARN=$(aws --region ${REGION} secretsmanager create-secret \
  --name MySecret --secret-string \
  '{"username":"shadowman", "password":"hunter2"}' \
  --query ARN --output text)

echo ${SECRET_ARN}
----
+
.Sample Output
[source,texinfo]
----
arn:aws:secretsmanager:eu-central-1:476025277093:secret:MySecret-mZjbYo
----

. Create IAM Access Policy document
+
[source,sh,role=copy]
----
cat << EOF > ${SECRETS_DIR}/policy.json
{
  "Version": "2012-10-17",
  "Statement": [{
      "Effect": "Allow",
      "Action": [
        "secretsmanager:GetSecretValue",
        "secretsmanager:DescribeSecret"
      ],
      "Resource": ["${SECRET_ARN}"]
      }]
}
EOF
----

. Create an IAM Access Policy
+
[source,sh,role=copy]
----
POLICY_ARN=$(aws --region ${REGION} --query Policy.Arn \
  --output text iam create-policy \
  --policy-name openshift-access-to-mysecret-policy \
  --policy-document file://${SECRETS_DIR}/policy.json)

echo ${POLICY_ARN}
----
+
.Sample Output
[source,texinfo]
----

----


. Create IAM Role trust policy document. Note the trust policy is locked down to the default service account of a namespace you will create later.
+
[source,sh,role=copy]
----
cat <<EOF > ${SECRETS_DIR}/trust-policy.json
{
  "Version": "2012-10-17",
  "Statement": [
  {
  "Effect": "Allow",
  "Condition": {
    "StringEquals" : {
      "${OIDC_ENDPOINT}:sub": ["system:serviceaccount:my-application:default"]
    }
  },
  "Principal": {
    "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/${OIDC_ENDPOINT}"
  },
  "Action": "sts:AssumeRoleWithWebIdentity"
  }
  ]
}
EOF
----

. Create IAM Role
+
[source,sh,role=copy]
----
ROLE_ARN=$(aws iam create-role --role-name openshift-access-to-mysecret \
  --assume-role-policy-document file://${SECRETS_DIR}/trust-policy.json \
  --query Role.Arn --output text)

echo ${ROLE_ARN}
----
+
.Sample Output
[source,texinfo]
----

----

. Attach Role to the Policy
+
[source,sh,role=copy]
----
aws iam attach-role-policy --role-name openshift-access-to-mysecret --policy-arn ${POLICY_ARN}
----

== Create an Application to use the secret from Secret Manager

. Create an OpenShift project (remember the service account from before?)
+
[source,sh,role=copy]
----
oc new-project my-application
----

. Annotate the default service account to use the STS Role
+
[source,sh,role=copy]
----
oc annotate -n my-application serviceaccount default \
  eks.amazonaws.com/role-arn=${ROLE_ARN}
----

. Create a secret provider class to access our secret
+
[source,sh,role=copy]
----
cat << EOF | oc apply -f -
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-application-aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "MySecret"
        objectType: "secretsmanager"
EOF
----

. Create a Pod using our secret
+
[source,sh,role=copy]
----
cat << EOF | oc apply -f -
---
apiVersion: v1
kind: Pod
metadata:
  name: my-application
  namespace: my-application
  labels:
    app: my-application
spec:
  volumes:
  - name: secrets-store-inline
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "my-application-aws-secrets"
  containers:
  - name: my-application
    image: k8s.gcr.io/e2e-test-images/busybox:1.29
    securityContext:
      privileged: false
      allowPrivilegeEscalation: true
    command:
      - "/bin/sleep"
      - "10000"
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
EOF
----

. Verify the Pod has the secret mounted
+
[source,sh,role=copy]
----
oc exec -it my-application -- cat /mnt/secrets-store/MySecret
----
+
.Sample Output
[source,texinfo]
----

----

== Cleanup

. Delete application
+
[source,sh,role=copy]
----
oc delete project my-application
----

. Delete the AWS provider
+
[source,sh,role=copy]
----
oc delete -f ${HOME}/aws-provider-installer.yaml
----

. Delete the secrets store csi driver
+
[source,sh,role=copy]
----
helm delete -n csi-secrets-store csi-secrets-store-driver
----

. Delete Security Context Constraints
+
[source,sh,role=copy]
----
oc adm policy remove-scc-from-user privileged \
  system:serviceaccount:csi-secrets-store:secrets-store-csi-driver

oc adm policy remove-scc-from-user privileged \
  system:serviceaccount:csi-secrets-store:csi-secrets-store-provider-aws
----

. Delete AWS Roles and Policies
+
[source,sh,role=copy]
----
aws iam detach-role-policy --role-name openshift-access-to-mysecret --policy-arn ${POLICY_ARN}

aws iam delete-role --role-name openshift-access-to-mysecret
aws iam delete-policy --policy-arn ${POLICY_ARN}
----

. Delete the Secrets Manager secret
+
[source,sh,role=copy]
----
aws secretsmanager --region ${REGION} delete-secret --secret-id ${SECRET_ARN}
----
