= Configuring a ROSA cluster to pull images from AWS Elastic Container Registry (ECR)

There are two options to use to authenticate wth Amazon ECR to pull images.

The traditional method is to create a pull secret for ecr.

.Example
[source,sh,role=copy]
----
oc create secret docker-registry ecr-pull-secret  \
  --docker-server=<registry id>.dkr.ecr.<region>.amazonaws.com  \
  --docker-username=AWS --docker-password=$(aws ecr get-login-password) \
  --namespace=hello-world
----

However Amazon ECR tokens expire every 12 hours which will mean you will need to re-authenticate every 12 hours either through scripting or do so manually.

A second, and preferred method, is to attach an ECR Policy to your cluster's worker machine profiles which this guide will walk you through.

== Attach ECR Policy Role

You can attach an ECR policy to your cluster giving the cluster permissions to pull images from your registries. ROSA worker machine instances comes with pre-defined IAM roles, named differently depending on whether its a STS cluster or a non-STS cluster.

=== STS Cluster Role

`ManagedOpenShift-Worker-Role` is the IAM role attached to ROSA STS compute instances.

=== Non-STS Cluster Role

`<cluster name>-<identifier>-worker-role` is the IAM role attached to ROSA non-STS compute instances.

[TIP]
====
To find the non-STS cluster role run the following command with your cluster name:

[source,sh,role=copy]
----
aws iam list-roles | grep <cluster_name>
----

.Sample Output
[source,texinfo]
----
"RoleName": "kevin-ecr-8227t-bootstrap-role", "Arn": "arn:aws: iam: : 660250927410: role/kevin-ecr-8227t-bootstrap-role",
"RoleName": "kevin-ecr-8227t-master-role", "Arn": "arn: aws: iam: : 660250927410: role/kevin-ecr-8227t-master-role",
"RoleName": "kevin-ecr-8227t-worker-role", "Arn": "arn: aws: iam: : 660250927410: role/kevin-ecr-8227t-worker-role",

[...]
----
====

== Configure ECR with ROSA

ECR has several pre-defined policies that give permissions to interact with the service. In the case of ROSA, we will be pulling images from ECR and will only need to add the `AmazonEC2ContainerRegistryReadOnly` policy.

. Add the `AmazonEC2ContainerRegistryReadOnly` policy to the `ManagedOpenShift-Worker-Role` for STS clusters (or the `<cluster name>-<identifier>-worker-role` for non-STS clusters).
+
.STS Example
[source,sh,role=copy]
----
aws iam attach-role-policy \
  --role-name ManagedOpenShift-Worker-Role \
  --policy-arn "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
----

. Set a variable for the repository name you want to create
+
[source,sh,role=copy]
----
export REGISTRY=hello-ecr
----

. Create a repository
+
[source,sh,role=copy]
----
aws ecr create-repository \
  --repository-name $REGISTRY \
  --image-scanning-configuration scanOnPush=true \
  --region $REGION
----
+
.Sample Output
[source,texinfo]
----
{
    "repository": {
        "repositoryArn": "arn:aws:ecr:eu-central-1:870651848115:repository/hello-ecr",
        "registryId": "870651848115",
        "repositoryName": "hello-ecr",
        "repositoryUri": "870651848115.dkr.ecr.eu-central-1.amazonaws.com/hello-ecr",
        "createdAt": "2023-07-27T09:30:51+00:00",
        "imageTagMutability": "MUTABLE",
        "imageScanningConfiguration": {
            "scanOnPush": true
        },
        "encryptionConfiguration": {
            "encryptionType": "AES256"
        }
    }
}
----

. Get the Registry ID and set an environment variable
+
[source,sh,role=copy]
----
export REGISTRYID=$(aws ecr describe-repositories --repository-name hello-ecr | jq -r '.repositories[].registryId')

echo ${REGISTRYID}
----
+
.Sample Output
[source,texinfo]
----
870651848115
----

. Log into ECR
+
[source,sh,role=copy]
----
podman login -u AWS -p $(aws ecr get-login-password --region ${REGION}) ${REGISTRYID}.dkr.ecr.${REGION}.amazonaws.com
----
+
.Sample Output
[source,texinfo]
----
WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available
WARN[0000] For using systemd, you may need to login using an user session
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1001` (possibly as root)
WARN[0000] Falling back to --cgroup-manager=cgroupfs
Login Succeeded!
WARN[0000] Failed to add pause process to systemd sandbox cgroup: exec: "dbus-launch": executable file not found in $PATH
----

. Pull an image
+
[source,sh,role=copy]
----
podman pull docker.io/openshift/hello-openshift:latest
----
+
.Sample Output
[source,texinfo]
----
Trying to pull docker.io/openshift/hello-openshift:latest...
Getting image source signatures
Copying blob 8b32988996c5 done
Copying blob 4f4fb700ef54 done
Copying config 7af3297a3f done
Writing manifest to image destination
Storing signatures
7af3297a3fb4487b740ed6798163f618e6eddea1ee5fa0ba340329fcae31c8f6
----

. Tag the image for ECR
+
[source,sh,role=copy]
----
podman tag docker.io/openshift/hello-openshift:latest ${REGISTRYID}.dkr.ecr.${REGION}.amazonaws.com/hello-ecr:latest
----

. Push the image to ECR
+
[source,sh,role=copy]
----
podman push ${REGISTRYID}.dkr.ecr.${REGION}.amazonaws.com/hello-ecr:latest
----
+
.Sample Output
[source,texinfo]
----
Getting image source signatures
Copying blob da0e4d9121c7 done
Copying blob 5f70bf18a086 done
Copying config 7af3297a3f done
Writing manifest to image destination
Storing signatures
----

== Deploy an application using the image from ECR

. Create an OpenShift project
+
[source,sh,role=copy]
----
oc new-project hello-ecr
----

. Create OpenShift pull secret for the new ECR registry
+
[source,sh,role=copy]
----
oc create secret docker-registry ecr-pull-secret \
  --docker-server=${REGISTRYID}.dkr.ecr.${REGION}.amazonaws.com \
  --docker-username=AWS \
  --docker-password=$(aws ecr get-login-password) \
  --namespace=hello-ecr
----
+
.Sample Output
[source,texinfo]
----
secret/ecr-pull-secret created
----

. Link the pull secret to your `default` service account:
+
[source,sh,role=copy]
----
oc secrets link default ecr-pull-secret --for=pull
----

. Create a new app using the image on ECR
+
[source,sh,role=copy]
----
oc new-app --name hello-ecr --image ${REGISTRYID}.dkr.ecr.${REGION}.amazonaws.com/hello-ecr:latest
----

. View a list of pods in the namespace you created:
+
[source,sh,role=copy]
----
oc get pods
----
+
.Sample Output
[source,texinfo]
----
NAME                         READY   STATUS    RESTARTS   AGE
hello-ecr-5668cb7969-zl7zl   1/1     Running   0          6s
----

== Clean up

. Simply delete the project you created to test pulling images:
+
[source,sh,role=copy]
----
oc delete project hello-ecr
----

You may also want to remove the `arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly` policy from the worker nodes if you do no want them to continue to have access to the ECR.
